### ISSUE TITLE
Update method signature with ruby 2.0 double-splat

### ISSUE THREAD

**Issue by nevans** [will3216/resque-better_unique#3]
https://github.com/will3216/resque-better_unique/blob/cccd4527a6435b8532addbc169fbe0c49676adda/lib/resque/plugins/better_unique.rb#L47

If we change the method signature to

```ruby
def unique_job(mode=:until_executed, **options)
```

Then we'll be able to use the default mode with other non-default options, e.g.

```ruby
unique_job timeout: 2.hours
```

The current code will interpret that as the mode being the options hash (which won't work out as the developer might have expected.

What do you think?
```

**Comment by will3216** [comment]
I like it! Wanna submit a PR?

**Comment by will3216** [comment]
Updated with https://github.com/will3216/resque-better_unique/pull/5
